services:
  remotearch:
    build:
      context: .
      dockerfile: addons/remotearch/Dockerfile
    image: selkies-arch-lxqt
    environment:
      SELKIES_MODE: websockets
      SELKIES_ENABLE_DUAL_MODE: "false"
      SELKIES_PORT: "8080"
      START_LXQT: "true"
      SELKIES_WAYLAND: "true"
      SELKIES_AUDIO_BITRATE: "192000"
      SELKIES_AUDIO_DEVICE_NAME: output.monitor
      PASSWD: "${PASSWD:-changeme}"
      DRI_NODE: ${DRI_NODE:-/dev/dri/renderD128}
      MESA_VK_DEVICE_SELECT: ${MESA_VK_DEVICE_SELECT:-8086:56a1}
      VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/intel_icd.json
    ports:
      - "${HOST_PORT:-3020}:8080"
    devices:
      - /dev/dri:/dev/dri
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./home:/home/arch
    shm_size: "2gb"
    restart: unless-stopped
