#!/bin/bash
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-ubuntu}"
mkdir -pm700 "${XDG_RUNTIME_DIR}"
chown -f "$(id -nu):$(id -ng)" "${XDG_RUNTIME_DIR}" 2>/dev/null || true
exec dbus-daemon --system --nofork --nosyslog --nopidfile --address="${DBUS_SYSTEM_BUS_ADDRESS:-unix:path=${XDG_RUNTIME_DIR}/dbus-system-bus}"
